config/routes.rb
Rails.application.routes.draw do
  # Devise setup for user and admin authentication
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Root route
  root to: 'products#index'

  # Products and Categories
  resources :products, only: [:show, :index]
  get 'categories/:id/products', to: 'categories#show', as: 'category_products'

  # Cart and Cart Items
  resource :cart, only: [:show] do
    post 'checkout', on: :member
  end

  resources :cart_items, only: [:create, :update, :destroy]

  # Orders
  resources :orders, only: [:show, :new, :create]
  # config/routes.rb
  get 'stripe_auto_post', to: 'carts#stripe_auto_post', as: 'stripe_auto_post'
  get 'order/cancel', to: 'orders#cancel', as: 'order_cancel'
  post 'create_stripe_session', to: 'checkout#create_stripe_session'
  # Users and Provinces
  resources :users, only: [:show, :edit, :update] do
    get 'orders', on: :member, as: 'order_history'
  end
  resources :provinces

  # Static Pages
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # Health Check
  get "up" => "rails/health#show", as: :rails_health_check



end

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'TechCrunch', root_path, class: 'navbar-brand' %>
    <!-- Navbar Toggler -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to 'About', about_path, class: 'nav-link' %>
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        <%= link_to 'On Sale', products_path(filter: 'on_sale'), class: 'nav-link' %>
        <%= link_to 'New Products', products_path(filter: 'new'), class: 'nav-link' %>
        <%= link_to 'Products', products_path, class: 'nav-link' %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Order History', order_history_user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to cart_path, class: 'nav-link' do %>
            <i class="fas fa-shopping-cart"></i> Cart
            <% if current_cart.present? %>
              <span class="badge bg-secondary"><%= current_cart.cart_items.count %></span>
            <% else %>
              <span class="badge bg-secondary">0</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechCrunch</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>

  <%= render 'layouts/navbar' %>

<div class="container-fluid">
<div class="row">
  <div class="col">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>